"""initial schema

Revision ID: f14fa8f18280
Revises:
Create Date: 2026-10-02 13:50:56.794938
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f14fa8f18280"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "author_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("colour", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "doi_record",
        sa.Column("doi", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=True),
        sa.Column("data", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("raw", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("doi"),
    )
    op.create_table(
        "flag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("colour", sa.String(), nullable=False),
        sa.Column("track", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "folder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jcr_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("affiliation", sa.String(), nullable=True),
        sa.Column("orcid", sa.String(length=19), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("student_aliases", sa.JSON(), nullable=False),
        sa.Column("student_outcomes", sa.JSON(), nullable=False),
        sa.Column("name_rejects", sa.JSON(), nullable=False),
        sa.Column("author_categories", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_merged_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("colour", sa.String(length=16), nullable=False),
        sa.Column("per_period", sa.Boolean(), nullable=False),
        sa.Column("key", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "venue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=True),
        sa.Column("kind_manual", sa.Boolean(), nullable=False),
        sa.Column("level_type", sa.String(length=16), nullable=True),
        sa.Column("level_rank", sa.String(), nullable=True),
        sa.Column("record_key", sa.String(), nullable=True),
        sa.Column("match_text", sa.String(), nullable=True),
        sa.Column("patterns", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("identifiers", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("hosts", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("joint", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venue_cache",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("badge", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("venue_cache", schema=None) as batch_op:
        batch_op.create_index("ix_venue_cache_source", ["source"], unique=False)

    op.create_table(
        "period",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["folder_id"], ["folder.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", "folder_id"),
    )
    op.create_table(
        "publication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("venue_manual", sa.Boolean(), nullable=False),
        sa.Column("venue_source", sa.String(length=32), nullable=True),
        sa.Column("rank_override", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("rank_note", sa.String(), nullable=True),
        sa.Column("kind_override", sa.String(length=32), nullable=True),
        sa.Column("doi_manual", sa.String(), nullable=True),
        sa.Column("year_override", sa.Integer(), nullable=True),
        sa.Column("author_pos_override", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("merge_locked", sa.Boolean(), nullable=False),
        sa.Column("missing", sa.Boolean(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("publication", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_publication_person_id"), ["person_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_publication_venue_id"), ["venue_id"], unique=False)

    op.create_table(
        "source_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("sync_state", sa.String(length=16), nullable=False),
        sa.Column("sync_started_at", sa.DateTime(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", "source", "external_id"),
    )
    op.create_table(
        "venue_key",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("example", sa.String(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("track", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("venue_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_venue_key_venue_id"), ["venue_id"], unique=False)

    op.create_table(
        "venue_text",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("raw", sa.String(), nullable=False),
        sa.Column("clean", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("via", sa.String(length=16), nullable=False),
        sa.Column("pattern_index", sa.Integer(), nullable=True),
        sa.Column("track", sa.String(), nullable=True),
        sa.Column("conflicts", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "raw"),
    )
    with op.batch_alter_table("venue_text", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_venue_text_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_venue_text_venue_id"), ["venue_id"], unique=False)

    op.create_table(
        "period_note",
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["period_id"], ["period.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publication_id"], ["publication.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("period_id", "publication_id"),
    )
    op.create_table(
        "period_tag",
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["period_id"], ["period.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publication_id"], ["publication.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("period_id", "publication_id", "tag_id"),
    )
    op.create_table(
        "publication_flag",
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("flag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["flag_id"], ["flag.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publication_id"], ["publication.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("publication_id", "flag_id"),
    )
    op.create_table(
        "publication_pdf",
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["publication_id"], ["publication.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("publication_id"),
    )
    op.create_table(
        "publication_tag",
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["publication_id"], ["publication.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("publication_id", "tag_id"),
    )
    op.create_table(
        "report",
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("tag_ids", sa.JSON(), nullable=False),
        sa.Column("number_format", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["period_id"], ["period.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("period_id"),
    )
    op.create_table(
        "source_pub",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("external_key", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("authors", sa.JSON(), nullable=False),
        sa.Column("author_pos", sa.Integer(), nullable=True),
        sa.Column("num_authors", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("venue", sa.String(), nullable=True),
        sa.Column("issn", sa.String(), nullable=True),
        sa.Column("venue_type", sa.String(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("doc_type", sa.String(), nullable=True),
        sa.Column("pdf_url", sa.String(), nullable=True),
        sa.Column("archival", sa.Boolean(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["link_id"], ["source_link.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publication_id"], ["publication.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_id", "external_key"),
    )
    with op.batch_alter_table("source_pub", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_pub_doi"), ["doi"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_source_pub_publication_id"), ["publication_id"], unique=False
        )

    op.create_table(
        "thesis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("thesis_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("student", sa.String(), nullable=True),
        sa.Column("supervisors", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("defence_date", sa.String(), nullable=True),
        sa.Column("start_date", sa.String(), nullable=True),
        sa.Column("discipline", sa.String(), nullable=True),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["link_id"], ["source_link.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_id", "thesis_id", "role"),
    )
    # ### end Alembic commands ###
    # The built-in tag for starred papers
    op.execute(
        "INSERT INTO tag (name, colour, per_period, key) VALUES ('starred', '#ff8f00', 1, 'starred')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thesis")
    with op.batch_alter_table("source_pub", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_pub_publication_id"))
        batch_op.drop_index(batch_op.f("ix_source_pub_doi"))

    op.drop_table("source_pub")
    op.drop_table("report")
    op.drop_table("publication_tag")
    op.drop_table("publication_pdf")
    op.drop_table("publication_flag")
    op.drop_table("period_tag")
    op.drop_table("period_note")
    with op.batch_alter_table("venue_text", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_venue_text_venue_id"))
        batch_op.drop_index(batch_op.f("ix_venue_text_key"))

    op.drop_table("venue_text")
    with op.batch_alter_table("venue_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_venue_key_venue_id"))

    op.drop_table("venue_key")
    op.drop_table("source_link")
    with op.batch_alter_table("publication", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publication_venue_id"))
        batch_op.drop_index(batch_op.f("ix_publication_person_id"))

    op.drop_table("publication")
    op.drop_table("period")
    with op.batch_alter_table("venue_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_venue_cache_source")

    op.drop_table("venue_cache")
    op.drop_table("venue")
    op.drop_table("tag")
    op.drop_table("person")
    op.drop_table("jcr_record")
    op.drop_table("folder")
    op.drop_table("flag")
    op.drop_table("doi_record")
    op.drop_table("author_category")
    op.drop_table("app_setting")
    # ### end Alembic commands ###
